name: Build and upload Buck2 binaries

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: 'ubuntu-22.04'
            triple: 'aarch64-unknown-linux-gnu'
            cross: true
          - os: 'ubuntu-22.04'
            triple: 'aarch64-unknown-linux-musl'
            cross: true
          - os: 'ubuntu-22.04'
            triple: 'x86_64-unknown-linux-gnu'
          # - os: 'ubuntu-22.04'
          #   triple: 'x86_64-unknown-linux-musl' # Doesn't build
          - os: 'macos-12'
            triple: 'aarch64-apple-darwin'
          - os: 'macos-12'
            triple: 'x86_64-apple-darwin'
          - os: 'windows-2022'
            triple: 'x86_64-pc-windows-msvc'
    runs-on: ${{ matrix.target.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly-2023-01-24
          targets: ${{ matrix.target.triple }}
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: buck2-upload
          key: ${{ matrix.target.triple }}
      - uses: actions-rs/install@v0.1
        if: matrix.target.cross
        with:
          crate: cross
          version: latest
      - name: Build
        shell: bash
        env:
          RUSTFLAGS: "-C strip=debuginfo"
        run: |
          if [ -n "${{ matrix.target.cross }}" ]; then
            CARGO=cross
          else
            CARGO=cargo
          fi
          $CARGO build --release --bin buck2 --target ${{ matrix.target.triple }}
      - name: Move binary to artifact/ (non-Windows)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          mkdir artifact
          zstd -z target/${{ matrix.target.triple }}/release/buck2 -o artifact/buck2-${{ matrix.target.triple }}.zst
      - name: Move binary to artifact/ (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          mkdir artifact
          zstd -z target/${{ matrix.target.triple }}/release/buck2.exe -o artifact/buck2-${{ matrix.target.triple }}.exe.zst
      - name: Upload (non-Windows)
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v3
        with:
          path: artifact/buck2-${{ matrix.target.triple }}.zst

      - name: Upload (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          path: artifact/buck2-${{ matrix.target.triple }}.exe.zst

  release:
    name: Upload Latest Build
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: mkdir ${{github.workspace}}/artifacts
      - uses: actions/download-artifact@v4.1.7
        with:
          path: ${{github.workspace}}/artifacts
      - name: Display structure of downloaded files
        run: |
          ls -R
        working-directory: ${{github.workspace}}/artifacts
      - uses: pyTooling/Actions/releaser@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'latest'
          files: ${{github.workspace}}/artifacts/**/buck2-*.zst
          rm: true
      - name: Summary
        run: |
          cat <<EOF >> $GITHUB_STEP_SUMMARY
          # Latest Build Complete! :rocket:
          For the public download links of these build artifacts, please see:
           <https://github.com/facebook/buck2/releases/tag/latest>
          EOF
